# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/cosmic64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y

    wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
    sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
    apt-get update
    apt-get install -y openjdk-8-jre
    apt-get install -y jenkins
  SHELL
end

